[package]
name = "simple"
version = "0.1.0"
authors = ["EliudArudo <eliudarudo@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"

rocket = "0.4.1"